name: Deploy to new-dev

on:
  push:
    branches:
      - development
  workflow_dispatch: 

jobs:
  redeploy_frontend:
    name: Deploy frontend to development
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: SSH Into Server and Deploy
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: 13.51.74.160
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /thirdexDev/thirdxui
            sudo git stash
            sudo git fetch --all
            sudo git checkout development
            sudo git pull origin development
            git log -1
            sudo npm install -f
            sudo npm run build
